name: PR_unit_tests

on:
  push:
    branches: [ master ]

jobs:
  test:
    name: Run unit tests on PR in main
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: set Up JDK 1.8
        uses: actions/setup-java@v1
        with: {java-version: 1.8}
      - name: Run unit tests
        run: bash ./gradlew test

        uses: actions/checkout@v2
      - name: Reports about errors
      - run: mkdir -p app/build/reports/tests/testDebugUnitTest

      - run: echo file:///home/runner/work/TestGithubActions/TestGithubActions/app/build/reports/tests/testDebugUnitTest/index.html > app/build/reports/tests/testDebugUnitTest/index.html

      - uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: app/build/reports/tests/testDebugUnitTest/index.html