name: PR_unit_tests

on:
  pull_request:
    branches:
      - "main"

jobs:
  Unit-test:
    name: run unit test on PR main
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with: {java-version: 1.8}
      - name: Run unit tests
        run: ./gradlew test